# Generated by Django 5.2.17 on 2026-09-10 19:07

import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models

import apps.notifications.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # recipient_email / email are CITEXT (04.8) — the extension must
        # exist before any table can use the type.
        CITextExtension(),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("recipient_email", apps.notifications.fields.CITextField()),
                ("client_id", models.UUIDField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("account_integrity", "Account integrity"),
                            ("consent", "Consent"),
                            ("commercial", "Commercial"),
                            ("async_completion", "Async completion"),
                            ("digest", "Digest"),
                            ("risk_alert", "Risk alert"),
                            ("operator_alert", "Operator alert"),
                        ],
                        max_length=40,
                    ),
                ),
                ("template_key", models.CharField(max_length=60)),
                ("template_version", models.CharField(max_length=20)),
                ("language", models.CharField(max_length=5)),
                (
                    "sender_role",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System"),
                            ("ADVISORY", "Advisory"),
                            ("OPERATOR_ALERTS", "Operator alerts"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_email", models.CharField(max_length=160)),
                ("subject", models.CharField(max_length=255)),
                ("provider", models.CharField(blank=True, default="", max_length=30)),
                ("provider_message_id", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("bounced", "Bounced"),
                            ("complained", "Complained"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "bounce_type",
                    models.CharField(
                        blank=True,
                        choices=[("hard", "Hard"), ("soft", "Soft")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("related_object_type", models.CharField(blank=True, max_length=40, null=True)),
                ("related_object_id", models.CharField(blank=True, max_length=60, null=True)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("bounced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_log",
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("account_integrity", "Account integrity"),
                            ("consent", "Consent"),
                            ("commercial", "Commercial"),
                            ("async_completion", "Async completion"),
                            ("digest", "Digest"),
                            ("risk_alert", "Risk alert"),
                            ("operator_alert", "Operator alert"),
                        ],
                        max_length=40,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_preference",
            },
        ),
        migrations.CreateModel(
            name="SuppressionList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", apps.notifications.fields.CITextField(unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("hard_bounce", "Hard bounce"),
                            ("complaint", "Complaint"),
                            ("manual", "Manual"),
                            ("unsubscribe_all", "Unsubscribe all"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("provider_webhook", "Provider webhook"),
                            ("admin", "Admin"),
                            ("user_action", "User action"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suppressions",
                        to="notifications.emaillog",
                    ),
                ),
            ],
            options={
                "db_table": "suppression_list",
            },
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["recipient_email", "-queued_at"], name="email_log_recipient_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(fields=["user", "-queued_at"], name="email_log_user_idx"),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(fields=["category", "-queued_at"], name="email_log_category_idx"),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                condition=models.Q(("status__in", ["queued", "failed"])),
                fields=["status"],
                name="email_log_open_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "category"), name="uniq_notification_preference_user_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("category__in", ["account_integrity", "consent"]), _negated=True),
                    ("is_enabled", True),
                    _connector="OR",
                ),
                name="notification_preference_transactional_always_enabled",
            ),
        ),
    ]
